# Generated by Django 5.1.7 on 2025-03-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="DoB",
            field=models.DateField(
                null=True, verbose_name="Date of Birth"
            ),
        ),
    ]
